#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Tests for the IntAct annotator."""

import unittest
from unittest.mock import Mock

import pandas as pd

from pyBiodatafuse.annotators import intact
from pyBiodatafuse.annotators.intact import (
    check_endpoint_intact,
    get_compound_interactions,
    get_gene_interactions,
)
from pyBiodatafuse.constants import INTACT_COMPOUND_INTERACT_COL, INTACT_INTERACT_COL


class TestIntact(unittest.TestCase):
    """Test the IntAct class."""

    def test_get_interactions(self):
        """Test the get_interactions function."""
        intact.check_endpoint_intact = Mock(return_value=True)

        bridgedb_dataframe = pd.DataFrame(
            {
                "identifier": ["TP53", "MDM2"],
                "identifier.source": ["HGNC", "HGNC"],
                "target": ["ENSG00000141510", "ENSG00000135679"],
                "target.source": ["Ensembl", "Ensembl"],
            }
        )

        obtained_data, metadata = get_gene_interactions(
            bridgedb_dataframe, interaction_type="gene_gene"
        )

        expected_data = pd.Series(
            [
                [
                    {
                        "interaction_id": "EBI-21879744",
                        "interactor_id_A": "EBI-3895853",
                        "interactor_id_B": "EBI-5279149",
                        "binary_interaction_id": 4493009,
                        "confidence_values": ["intact-miscore:0.35"],
                        "score": 0.35,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "anti tag coip",
                        "detection_method_id": "MI:0007",
                        "host_organism": "Homo sapiens HEK293T embryonic kidney cell",
                        "interactor_A_name": "p04637-2",
                        "interactor_B_name": "q00987-11",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "TP53",
                        "molecule_B": "MDM2",
                        "id_A": "P04637-2",
                        "id_B": "Q00987-11",
                        "pubmed_publication_id": "28514442",
                        "ensembl": "ENSG00000141510",
                        "altIdsA": [
                            "P04637-2 (uniprotkb)",
                            "ENSP00000391127.2 (ensembl)",
                            "EBI-3895853 (intact)",
                        ],
                        "altIdsB": [
                            "Q00987-11 (uniprotkb)",
                            "EBI-5279149 (intact)",
                            "ENSP00000258149.6 (ensembl)",
                        ],
                        "intact_link_to": "MDM2",
                    },
                ],
                [
                    {
                        "interaction_id": "EBI-1551596",
                        "interactor_id_A": "EBI-389668",
                        "interactor_id_B": "EBI-389668",
                        "binary_interaction_id": 2180886,
                        "confidence_values": ["intact-miscore:0.74"],
                        "score": 0.74,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "physical association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "anti tag coip",
                        "detection_method_id": "MI:0007",
                        "host_organism": "Homo sapiens HEK293 embryonic kidney cell",
                        "interactor_A_name": "mdm2_human",
                        "interactor_B_name": "mdm2_human",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "MDM2",
                        "molecule_B": "MDM2",
                        "id_A": "Q00987",
                        "id_B": "Q00987",
                        "pubmed_publication_id": "17936559",
                        "ensembl": "ENSG00000135679",
                        "altIdsA": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "altIdsB": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "intact_link_to": "MDM2",
                    },
                    {
                        "interaction_id": "EBI-4307418",
                        "interactor_id_A": "EBI-389668",
                        "interactor_id_B": "EBI-389668",
                        "binary_interaction_id": 9859622,
                        "confidence_values": ["intact-miscore:0.74"],
                        "score": 0.74,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "physical association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "two hybrid array",
                        "detection_method_id": "MI:0397",
                        "host_organism": "Saccharomyces cerevisiae (Baker's yeast)",
                        "interactor_A_name": "mdm2_human",
                        "interactor_B_name": "mdm2_human",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "MDM2",
                        "molecule_B": "MDM2",
                        "id_A": "Q00987",
                        "id_B": "Q00987",
                        "pubmed_publication_id": "22493164",
                        "ensembl": "ENSG00000135679",
                        "altIdsA": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "altIdsB": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "intact_link_to": "MDM2",
                    },
                    {
                        "interaction_id": "EBI-7156290",
                        "interactor_id_A": "EBI-389668",
                        "interactor_id_B": "EBI-389668",
                        "binary_interaction_id": 12259773,
                        "confidence_values": ["intact-miscore:0.74"],
                        "score": 0.74,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "physical association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "anti tag coip",
                        "detection_method_id": "MI:0007",
                        "host_organism": "Homo sapiens HEK293 embryonic kidney cell",
                        "interactor_A_name": "mdm2_human",
                        "interactor_B_name": "mdm2_human",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "MDM2",
                        "molecule_B": "MDM2",
                        "id_A": "Q00987",
                        "id_B": "Q00987",
                        "pubmed_publication_id": "17159902",
                        "ensembl": "ENSG00000135679",
                        "altIdsA": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "altIdsB": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "intact_link_to": "MDM2",
                    },
                    {
                        "interaction_id": "EBI-7156376",
                        "interactor_id_A": "EBI-389668",
                        "interactor_id_B": "EBI-389668",
                        "binary_interaction_id": 12259846,
                        "confidence_values": ["intact-miscore:0.74"],
                        "score": 0.74,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "physical association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "anti bait coip",
                        "detection_method_id": "MI:0006",
                        "host_organism": "Homo sapiens HEK293 embryonic kidney cell",
                        "interactor_A_name": "mdm2_human",
                        "interactor_B_name": "mdm2_human",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "MDM2",
                        "molecule_B": "MDM2",
                        "id_A": "Q00987",
                        "id_B": "Q00987",
                        "pubmed_publication_id": "17159902",
                        "ensembl": "ENSG00000135679",
                        "altIdsA": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "altIdsB": [
                            "Q13226 (uniprotkb)",
                            "EBI-389668 (intact)",
                            "Q8WYJ1 (uniprotkb)",
                            "EBI-28980679 (intact)",
                            "A8K2S6 (uniprotkb)",
                            "Q8WYJ2 (uniprotkb)",
                            "Q13301 (uniprotkb)",
                            "Q00987 (uniprotkb)",
                            "Q9UGI3 (uniprotkb)",
                            "Q13300 (uniprotkb)",
                            "Q9UMT8 (uniprotkb)",
                            "Q13297 (uniprotkb)",
                            "Q71TW9 (uniprotkb)",
                            "Q13298 (uniprotkb)",
                            "Q53XW0 (uniprotkb)",
                            "A6NL51 (uniprotkb)",
                            "ENSP00000444430.2 (ensembl)",
                            "Q13299 (uniprotkb)",
                        ],
                        "intact_link_to": "MDM2",
                    },
                    {
                        "interaction_id": "EBI-21879744",
                        "interactor_id_A": "EBI-3895853",
                        "interactor_id_B": "EBI-5279149",
                        "binary_interaction_id": 4493009,
                        "confidence_values": ["intact-miscore:0.35"],
                        "score": 0.35,
                        "biological_role_A": "unspecified role",
                        "biological_role_B": "unspecified role",
                        "type": "association",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "anti tag coip",
                        "detection_method_id": "MI:0007",
                        "host_organism": "Homo sapiens HEK293T embryonic kidney cell",
                        "interactor_A_name": "p04637-2",
                        "interactor_B_name": "q00987-11",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Homo sapiens",
                        "molecule_A": "TP53",
                        "molecule_B": "MDM2",
                        "id_A": "P04637-2",
                        "id_B": "Q00987-11",
                        "pubmed_publication_id": "28514442",
                        "ensembl": "ENSG00000135679",
                        "altIdsA": [
                            "P04637-2 (uniprotkb)",
                            "ENSP00000391127.2 (ensembl)",
                            "EBI-3895853 (intact)",
                        ],
                        "altIdsB": [
                            "Q00987-11 (uniprotkb)",
                            "EBI-5279149 (intact)",
                            "ENSP00000258149.6 (ensembl)",
                        ],
                        "intact_link_to": "TP53",
                    },
                ],
            ]
        )
        expected_data.name = INTACT_INTERACT_COL

        pd.testing.assert_series_equal(obtained_data[INTACT_INTERACT_COL], expected_data)
        self.assertIsInstance(metadata, dict)

    def test_get_compound_interactions(self):
        """Test the get_compound_interactions function."""
        intact.check_endpoint_intact = Mock(return_value=True)

        bridgedb_dataframe = pd.DataFrame(
            {
                "identifier": ["15361"],
                "identifier.source": ["ChEBI"],
                "target": ["CHEBI:15361"],
                "target.source": ["ChEBI"],
            }
        )

        obtained_data, metadata = get_compound_interactions(bridgedb_dataframe)

        expected_data = pd.Series(
            [
                [
                    {
                        "interaction_id": "EBI-9301798",
                        "interactor_id_A": "EBI-9096",
                        "interactor_id_B": "EBI-6621808",
                        "binary_interaction_id": 13894862,
                        "confidence_values": ["intact-miscore:0.44"],
                        "score": 0.44,
                        "biological_role_A": "enzyme",
                        "biological_role_B": "enzyme target",
                        "type": "enzymatic reaction",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "enzymatic study",
                        "detection_method_id": "MI:0415",
                        "host_organism": "In vitro",
                        "interactor_A_name": "ilvb_yeast",
                        "interactor_B_name": "pyruvate",
                        "interactor_A_species": "Saccharomyces cerevisiae",
                        "interactor_B_species": "Chemical synthesis (Chemical synthesis)",
                        "molecule_A": "ILV2",
                        "molecule_B": "pyruvate",
                        "id_A": "P07342",
                        "id_B": "CHEBI:15361",
                        "pubmed_publication_id": "16390333",
                        "ensembl": "CHEBI:15361",
                        "altIdsA": [
                            "P07342 (uniprotkb)",
                            "D6VZT1 (uniprotkb)",
                            "EBI-9096 (intact)",
                        ],
                        "altIdsB": ["CHEBI:15361 (chebi)", "EBI-6621808 (intact)"],
                        "intact_link_to": None,
                    },
                    {
                        "interaction_id": "EBI-6621805",
                        "interactor_id_A": "EBI-372327",
                        "interactor_id_B": "EBI-6621808",
                        "binary_interaction_id": 11900151,
                        "confidence_values": ["intact-miscore:0.44"],
                        "score": 0.44,
                        "biological_role_A": "enzyme",
                        "biological_role_B": "enzyme target",
                        "type": "enzymatic reaction",
                        "stoichiometry_A": "0-0",
                        "stoichiometry_B": "0-0",
                        "detection_method": "oxidoreduct assay",
                        "detection_method_id": "MI:0979",
                        "host_organism": "In vitro",
                        "interactor_A_name": "ldha_human",
                        "interactor_B_name": "pyruvate",
                        "interactor_A_species": "Homo sapiens",
                        "interactor_B_species": "Chemical synthesis (Chemical synthesis)",
                        "molecule_A": "LDHA",
                        "molecule_B": "pyruvate",
                        "id_A": "P00338",
                        "id_B": "CHEBI:15361",
                        "pubmed_publication_id": "23523103",
                        "ensembl": "CHEBI:15361",
                        "altIdsA": [
                            "ENSP00000395337.3 (ensembl)",
                            "Q53G53 (uniprotkb)",
                            "EBI-372327 (intact)",
                            "D3DQY3 (uniprotkb)",
                            "F8W819 (uniprotkb)",
                            "B7Z5E3 (uniprotkb)",
                            "ENSP00000445331.1 (ensembl)",
                            "ENSP00000500953.1 (ensembl)",
                            "Q9UDE9 (uniprotkb)",
                            "Q9UDE8 (uniprotkb)",
                            "Q6IBM7 (uniprotkb)",
                            "ENSP00000499898.1 (ensembl)",
                            "Q6ZNV1 (uniprotkb)",
                            "P00338 (uniprotkb)",
                            "B4DKQ2 (uniprotkb)",
                            "ENSP00000499977.1 (ensembl)",
                        ],
                        "altIdsB": ["CHEBI:15361 (chebi)", "EBI-6621808 (intact)"],
                        "intact_link_to": None,
                    },
                ]
            ]
        )
        expected_data.name = INTACT_COMPOUND_INTERACT_COL

        pd.testing.assert_series_equal(obtained_data[INTACT_COMPOUND_INTERACT_COL], expected_data)
        self.assertIsInstance(metadata, dict)
