PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pr: <http://purl.obolibrary.org/obo/pr#>

SELECT ?gene ?geneLabel ?processLabel
WHERE {
    ?gene a obo:NCIT_C16612 ;
          rdfs:label ?geneLabel ;
          sio:SIO_000068 ?process .
    
    ?process rdfs:label ?processLabel ;
             rdfs:subClassOf obo:GO_0008150 .
    
    ?protein pr:has_gene_template ?gene .

    # Retrieve agonist drugs targeting the protein
    ?agonistDrug a sio:SIO_010038 ;
                 obo:RO_0018027 ?protein ;
                 sio:SIO_000300 ?clinicalStatusAgonist .

    # Retrieve antagonist drugs targeting the protein with specific status
    ?antagonistDrug a sio:SIO_010038 ;
                    obo:RO_0018029 ?protein ;
                    sio:SIO_000300 obo:OPMI_0000371 .

    # Filter for clinical status 4 or approved status for agonists
    FILTER(?clinicalStatusAgonist = obo:OPMI_0000371)
}