PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pr: <http://purl.obolibrary.org/obo/pr#>

SELECT DISTINCT ?drug ?drugLabel (COUNT(DISTINCT ?ae) AS ?adverseEventCount)
WHERE {
    ?gene a obo:NCIT_C16612 ;
          rdfs:label ?geneLabel .
    ?protein pr:has_gene_template ?gene ;
             rdfs:label ?proteinLabel ;
             sio:SIO_000068 ?ppi .

    ?ppi sio:SIO_000216 ?score .
    ?score sio:has_value ?scoreValue .
    FILTER(?scoreValue > 0.8)

    ?drug ?predicate ?protein ;
          rdfs:label ?drugLabel ;
          sio:SIO_000248 ?ae .

    ?ae rdfs:label ?aeLabel .

    VALUES ?predicate { obo:RO_0018027 obo:RO_0018029 }
}
GROUP BY ?drug ?drugLabel

ORDER BY DESC(?adverseEventCount)