SELECT ?aop ?aop_title ?chemical ?cas_id ?compound_name
       ?ao ?ao_label ?life_stage ?biological_process ?taxon
       (REPLACE(STR(?Ensembl), "https://identifiers.org/ensembl/", "") AS ?Ensembl)
       ?pubchem_compound ?chembl_compound
WHERE {
        VALUES ?pubchem_compound { $compounds }
    ?aop a aopo:AdverseOutcomePathway ;
         nci:C54571 ?stressor ;
         dc:title ?aop_title ;
         aopo:has_adverse_outcome ?ao .
             
    ?ao rdfs:label ?ao_label ;
        aopo:LifeStageContext ?life_stage .
    OPTIONAL {
      ?ao edam:data_1025 ?object .
      ?object skos:exactMatch ?id .
      ?id a edam:data_1033 ; 
          edam:data_1033 ?Ensembl .
    }

    OPTIONAL {
      ?ao <http://purl.obolibrary.org/obo/GO_0008150> ?biological_process .
      FILTER(STRSTARTS(STR(?biological_process), "http://purl.obolibrary.org/obo/GO"))
    }

    OPTIONAL {
      ?ao ncbitaxon:131567 ?taxon .
      FILTER(STRSTARTS(STR(?taxon), "http://purl.bioontology.org/ontology/NCBITAXON/"))
    }

    ?stressor aopo:has_chemical_entity ?chemical .
    ?chemical cheminf:000446 ?cas_id ;
              dc:title ?compound_name .

    # -- Match PubChem (OPTIONAL) --
    OPTIONAL {
      ?chemical skos:exactMatch ?pubchem_compound .
      FILTER(STRSTARTS(STR(?pubchem_compound), "https://identifiers.org/pubchem.compound/"))
    }

    # -- Match ChEMBL (OPTIONAL) --
    OPTIONAL {
      ?chemical skos:exactMatch ?chembl_compound .
      FILTER(STRSTARTS(STR(?chembl_compound), "https://identifiers.org/chembl.compound/"))
    }
}

