SELECT DISTINCT ?gene_id ?description ?disease_score ?source #?xref #?sub_class_of
FROM <http://rdf.disgenet.org> 
WHERE {
    VALUES ?entrez_id { $gene_list }
    BIND(CONCAT("http://identifiers.org/ncbigene/", STR(?entrez_id)) AS ?gene_id_str)
    BIND(URI(?gene_id_str) AS ?gene_id)
    ?gda sio:SIO_000628 ?disease,?gene_id .
    ?disease rdf:type ncit:C7057 .
    ?disease rdfs:label ?description .
    #?disease skos:exactMatch ?xref .
    #?disease rdfs:subClassOf ?sub_class_of .
    ?gda sio:SIO_000216 ?score . 
    ?gda sio:SIO_000253 ?source . 
    ?score sio:SIO_000300 ?disease_score .
    ?gene_id rdf:type ncit:C16612 . 
}