SELECT ?gene ?geneId ?article ?pubmed
WHERE {
  VALUES ?geneId { $gene_list }
  ?gene wdt:P351 ?geneId .
  { ?article wdt:P921 ?gene ; wdt:P698 ?pubmed }
  UNION
  { ?article wdt:P921/wdt:P702 ?gene ; wdt:P698 ?pubmed }
}
