SELECT ?geneId ?pathwayId ?pathwayLabel ?geneCount
WHERE {
	
  	VALUES ?geneId { $gene_list }
  	BIND(IRI(CONCAT("https://identifiers.org/ncbigene/", ?geneId)) AS ?geneIdUrl)
	
	?geneProduct a wp:GeneProduct .
	?geneProduct rdfs:label ?geneLabel .
    ?geneProduct wp:bdbEntrezGene ?geneIdUrl .
	?geneProduct dcterms:isPartOf ?pathway .

	?pathway a wp:Pathway .
  	?pathway dc:title ?pathwayLabel .
	?pathway dcterms:identifier ?pathwayId .
  
  	{
    	SELECT ?pathway (count(distinct ?gene) AS ?geneCount) 
        WHERE {
          
          ?gene a wp:GeneProduct .
		  ?gene dcterms:isPartOf ?pathway .
        
        } GROUP BY ?pathway  
    }
}
